package cmd

import "github.com/spf13/cobra"

func init() {
	rootCmd.AddCommand(renewalCmd)

}

RMQ_HOST=localhost
RMQ_PORT=5672
RMQ_USER=admin
RMQ_PASS=admin

RMQ_AUTOACK=false
RMQ_EXCHANGETYPE=direct
RMQ_EXCHANGEDURABILITY=false
RMQ_QUEUEDURABILITY=true

RMQ_RENEWALTHROTTLE=1
RMQ_RENEWALEXCHANGE=E_RENEWAL
RMQ_RENEWALQUEUE=Q_RENEWAL
RMQ_RENEWALDATATYPE=application/json
RMQ_RENEWALTPS=1000

RMQ_PRERENEWALTHROTTLE=1
RMQ_PRERENEWALEXCHANGE=E_PRERENEWAL
RMQ_PRERENEWALQUEUE=Q_PRERENEWAL
RMQ_PRERENEWALDATATYPE=application/json
RMQ_PRERENEWALTPS=1000

RMQ_RETRYTHROTTLE=1
RMQ_RETRYEXCHANGE=E_RETRY
RMQ_RETRYQUEUE=Q_RETRY
RMQ_RETRYDATATYPE=application/json
RMQ_RETRYTPS=1000

RMQ_TRIALTHROTTLE=1
RMQ_TRIALEXCHANGE=E_TRIAL
RMQ_TRIALQUEUE=Q_TRIAL
RMQ_TRIALTYPE=application/json
RMQ_TRIALTPS=1000
